### ISSUE TITLE
MobX requires global 'Symbol' to be available or polyfilled

### ISSUE THREAD

**Issue by dawnyu** [shenpvip/taro3-react-mobx-tailwind-template#1]
启动报错

![image](https://user-images.githubusercontent.com/8233022/141746757-8c5259ba-bdd2-4b62-969a-3ae612dbdf69.png)

**Comment by ifocus9** [comment]
已更新，重新拉一下代码试试

**Comment by dawnyu** [comment]
问题还是一样，支付宝小程序开发工具版本是2.5.3

**Comment by ZhengKehang** [comment]
遇到同样的问题

**Comment by nayo-z-a-h** [comment]
想问下这个问题怎么搞定的？？求大佬指教

**Comment by dawnyu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    降低mobx版本。。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                yuleiming
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        07/14/2022 18:50
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [shenpvip/taro-template] MobX requires global 'Symbol' to be available or polyfilled (Issue #1)
        
      
    
  
  

想问下这个问题怎么搞定的？？求大佬指教



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by nayo-z-a-h** [comment]
> 



> 字体{行高：1.6；} ul,ol{ padding-left: 20px; 列表样式位置：内部；} 降低mobx版本。。 yuleiming ***@***.***
> […](#)
> ---- 已回复消息 ---- 来自 ***@***.***> 日期 07/14/2022 18:50 至 ***@***.***> 抄送 ***@ ***.***> , ***@***.***> 主题回复：[shenpvip/taro-template] MobX 要求全局“符号”可用或填充（问题#1）想问下这个问题怎么搞定的？ >
搞定了。我的这边主要是想用mobx6+的写法，但是用了6，一直报这个错。我按照楼主的这个版本重新引入了一次就好了。谢谢~

**Comment by blin17** [comment]
你么用什么版本？我一直遇到这个问题

**Comment by ifocus9** [comment]
> 你么用什么版本？我一直遇到这个问题

描述具体一点，编译成微信小程序报错吗
