### ISSUE TITLE
你这个封装的httpService.ts不对

### ISSUE THREAD

**Issue by yrmatou** [shenpvip/taro3-react-mobx-tailwind-template#2]
![1654754077(1)](https://user-images.githubusercontent.com/21699695/172774468-456126f2-911f-476a-88b7-771925c861a4.png)
页面内用直接报这个
![1654754094(1)](https://user-images.githubusercontent.com/21699695/172774553-ae9de29f-30af-401c-b417-de6c5b20b299.png)

**Comment by ifocus9** [comment]
你useStore在哪用的，看报错你用错位置了吧
